//==============================================================================
//  OS/2 PM C++ Resource Header - "HumaNeko - A human 'Neko' for OS/2"
//
//  This file consists of all the constant identifiers used in the resource file
//
//  Written By Eric A. Wolf
//  Last Modified: December 22, 1993
//==============================================================================

#define GENERAL_HELP	        5
#define PRODUCT_INFO	        3
#define UPDATE_FREQUENCY	110
#define NEKO_STEPS	        103
#define STEP_RATE	        103
#define MOUSE_SENSITIVITY	102
#define OPTIONS_DIALOG	        2
#define PLAY_MODE_CHASE	        402
#define PLAY_MODE_RUN	        401
#define OPTIONS_PLAY_MODE	202
#define OPTIONS_SETTINGS	201
#define OPTIONS_EXIT	        204
#define HELP_GENERAL_HELP	301
#define HELP_PRODUCT_INFO	302
#define MENU_OPTIONS	        101
#define MENU_HELP	        102
#define MENUBAR	                1

